// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: hikes.sql

package admin

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHike = `-- name: CreateHike :one

INSERT INTO hikes (
    title_ru, 
    title_en, 
    description_ru, 
    description_en,
    starts_at, 
    ends_at, 
    photo_file_id, 
    is_published
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id
`

type CreateHikeParams struct {
	TitleRu       string      `db:"title_ru" json:"title_ru"`
	TitleEn       pgtype.Text `db:"title_en" json:"title_en"`
	DescriptionRu string      `db:"description_ru" json:"description_ru"`
	DescriptionEn pgtype.Text `db:"description_en" json:"description_en"`
	StartsAt      time.Time   `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time   `db:"ends_at" json:"ends_at"`
	PhotoFileID   pgtype.Text `db:"photo_file_id" json:"photo_file_id"`
	IsPublished   bool        `db:"is_published" json:"is_published"`
}

// =========================================
// HIKES
// =========================================
func (q *Queries) CreateHike(ctx context.Context, arg CreateHikeParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHike,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.StartsAt,
		arg.EndsAt,
		arg.PhotoFileID,
		arg.IsPublished,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteHike = `-- name: DeleteHike :exec
DELETE FROM hikes WHERE id = $1
`

func (q *Queries) DeleteHike(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHike, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one

SELECT id, hike_id, user_id, status, taken_by_admin_id
FROM bookings WHERE id = $1
`

type GetBookingByIDRow struct {
	ID             int32       `db:"id" json:"id"`
	HikeID         int32       `db:"hike_id" json:"hike_id"`
	UserID         int32       `db:"user_id" json:"user_id"`
	Status         string      `db:"status" json:"status"`
	TakenByAdminID pgtype.Int4 `db:"taken_by_admin_id" json:"taken_by_admin_id"`
}

// =========================================
// BOOKINGS
// =========================================
func (q *Queries) GetBookingByID(ctx context.Context, id int32) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.HikeID,
		&i.UserID,
		&i.Status,
		&i.TakenByAdminID,
	)
	return i, err
}

const getHikeByID = `-- name: GetHikeByID :one
SELECT id, title_ru, title_en, description_ru, description_en, starts_at, ends_at, photo_file_id, is_published, created_at, updated_at, image_path FROM hikes WHERE id = $1
`

func (q *Queries) GetHikeByID(ctx context.Context, id int32) (Hike, error) {
	row := q.db.QueryRow(ctx, getHikeByID, id)
	var i Hike
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.StartsAt,
		&i.EndsAt,
		&i.PhotoFileID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImagePath,
	)
	return i, err
}

const listActualHikes = `-- name: ListActualHikes :many
SELECT id, title_ru, starts_at, ends_at, is_published
FROM hikes
WHERE is_published = true AND ends_at >= now()
ORDER BY starts_at ASC
LIMIT $1 OFFSET $2
`

type ListActualHikesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListActualHikesRow struct {
	ID          int32     `db:"id" json:"id"`
	TitleRu     string    `db:"title_ru" json:"title_ru"`
	StartsAt    time.Time `db:"starts_at" json:"starts_at"`
	EndsAt      time.Time `db:"ends_at" json:"ends_at"`
	IsPublished bool      `db:"is_published" json:"is_published"`
}

func (q *Queries) ListActualHikes(ctx context.Context, arg ListActualHikesParams) ([]ListActualHikesRow, error) {
	rows, err := q.db.Query(ctx, listActualHikes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActualHikesRow
	for rows.Next() {
		var i ListActualHikesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminBookings = `-- name: ListAdminBookings :many
SELECT
    b.id,
    b.hike_id,
    h.title_ru AS hike_title,
    b.user_id,
    COALESCE(u.full_name, '') AS user_name,
    u.tg_user_id AS user_tg_id,
    b.status,
    b.taken_at,
    b.created_at
FROM bookings b
JOIN hikes h ON h.id = b.hike_id
JOIN telegram_users u ON u.id = b.user_id
WHERE
    b.taken_by_admin_id = $1
    AND b.status IN ('in_progress', 'confirmed')
ORDER BY
    b.created_at DESC
`

type ListAdminBookingsRow struct {
	ID        int32              `db:"id" json:"id"`
	HikeID    int32              `db:"hike_id" json:"hike_id"`
	HikeTitle string             `db:"hike_title" json:"hike_title"`
	UserID    int32              `db:"user_id" json:"user_id"`
	UserName  string             `db:"user_name" json:"user_name"`
	UserTgID  int64              `db:"user_tg_id" json:"user_tg_id"`
	Status    string             `db:"status" json:"status"`
	TakenAt   pgtype.Timestamptz `db:"taken_at" json:"taken_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAdminBookings(ctx context.Context, takenByAdminID pgtype.Int4) ([]ListAdminBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAdminBookings, takenByAdminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminBookingsRow
	for rows.Next() {
		var i ListAdminBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.HikeID,
			&i.HikeTitle,
			&i.UserID,
			&i.UserName,
			&i.UserTgID,
			&i.Status,
			&i.TakenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHikes = `-- name: ListHikes :many
SELECT 
    id, 
    title_ru, 
    description_ru,
    title_en,
    description_en,
    starts_at, 
    ends_at, 
    is_published, 
    created_at 
FROM 
    hikes 
ORDER BY is_published DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListHikesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListHikesRow struct {
	ID            int32       `db:"id" json:"id"`
	TitleRu       string      `db:"title_ru" json:"title_ru"`
	DescriptionRu string      `db:"description_ru" json:"description_ru"`
	TitleEn       pgtype.Text `db:"title_en" json:"title_en"`
	DescriptionEn pgtype.Text `db:"description_en" json:"description_en"`
	StartsAt      time.Time   `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time   `db:"ends_at" json:"ends_at"`
	IsPublished   bool        `db:"is_published" json:"is_published"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) ListHikes(ctx context.Context, arg ListHikesParams) ([]ListHikesRow, error) {
	rows, err := q.db.Query(ctx, listHikes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHikesRow
	for rows.Next() {
		var i ListHikesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.DescriptionRu,
			&i.TitleEn,
			&i.DescriptionEn,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsPublished,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPublished = `-- name: SetPublished :exec
UPDATE hikes
SET is_published = $1, updated_at = now()
WHERE id = $2
`

type SetPublishedParams struct {
	IsPublished bool  `db:"is_published" json:"is_published"`
	ID          int32 `db:"id" json:"id"`
}

func (q *Queries) SetPublished(ctx context.Context, arg SetPublishedParams) error {
	_, err := q.db.Exec(ctx, setPublished, arg.IsPublished, arg.ID)
	return err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2
WHERE id = $1
RETURNING id, hike_id, user_id, status, note, created_at, taken_by_admin_id, taken_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID        int32  `db:"id" json:"id"`
	NewStatus string `db:"new_status" json:"new_status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.NewStatus)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.HikeID,
		&i.UserID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.TakenByAdminID,
		&i.TakenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHike = `-- name: UpdateHike :one
UPDATE hikes SET
    title_ru       = $2,
    title_en       = $3,
    description_ru = $4,
    description_en = $5,
    starts_at      = $6,
    ends_at        = $7,
    photo_file_id  = $8,
    is_published   = $9,
    updated_at     = $10
WHERE id = $1
RETURNING id, title_ru, title_en, description_ru, description_en, starts_at, ends_at, photo_file_id, is_published, created_at, updated_at, image_path
`

type UpdateHikeParams struct {
	ID            int32       `db:"id" json:"id"`
	TitleRu       string      `db:"title_ru" json:"title_ru"`
	TitleEn       pgtype.Text `db:"title_en" json:"title_en"`
	DescriptionRu string      `db:"description_ru" json:"description_ru"`
	DescriptionEn pgtype.Text `db:"description_en" json:"description_en"`
	StartsAt      time.Time   `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time   `db:"ends_at" json:"ends_at"`
	PhotoFileID   pgtype.Text `db:"photo_file_id" json:"photo_file_id"`
	IsPublished   bool        `db:"is_published" json:"is_published"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateHike(ctx context.Context, arg UpdateHikeParams) (Hike, error) {
	row := q.db.QueryRow(ctx, updateHike,
		arg.ID,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.StartsAt,
		arg.EndsAt,
		arg.PhotoFileID,
		arg.IsPublished,
		arg.UpdatedAt,
	)
	var i Hike
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.StartsAt,
		&i.EndsAt,
		&i.PhotoFileID,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImagePath,
	)
	return i, err
}

const updateImagePath = `-- name: UpdateImagePath :exec
UPDATE hikes SET image_path = $2 WHERE id = $1
`

type UpdateImagePathParams struct {
	ID        int32       `db:"id" json:"id"`
	ImagePath pgtype.Text `db:"image_path" json:"image_path"`
}

func (q *Queries) UpdateImagePath(ctx context.Context, arg UpdateImagePathParams) error {
	_, err := q.db.Exec(ctx, updateImagePath, arg.ID, arg.ImagePath)
	return err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one

INSERT INTO telegram_users (tg_user_id, tg_username, full_name, lang)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tg_user_id)
DO UPDATE SET
    tg_username = EXCLUDED.tg_username,
    full_name   = EXCLUDED.full_name,
    lang        = EXCLUDED.lang
RETURNING id
`

type UpsertTelegramUserParams struct {
	TgUserID   int64       `db:"tg_user_id" json:"tg_user_id"`
	TgUsername pgtype.Text `db:"tg_username" json:"tg_username"`
	FullName   pgtype.Text `db:"full_name" json:"full_name"`
	Lang       string      `db:"lang" json:"lang"`
}

// =========================================
// TELEGRAM USERS
// =========================================
func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.TgUserID,
		arg.TgUsername,
		arg.FullName,
		arg.Lang,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
