// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: hikes.sql

package client

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminIfNotExists = `-- name: CreateAdminIfNotExists :exec
INSERT INTO admins (id)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateAdminIfNotExists(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, createAdminIfNotExists, id)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (hike_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (hike_id, user_id) DO NOTHING
RETURNING id
`

type CreateBookingParams struct {
	HikeID int32  `db:"hike_id" json:"hike_id"`
	UserID int32  `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (int32, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.HikeID, arg.UserID, arg.Status)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getHike = `-- name: GetHike :one
SELECT id, title_ru, starts_at, ends_at
FROM hikes
WHERE id = $1 AND is_published = true
`

type GetHikeRow struct {
	ID       int32     `db:"id" json:"id"`
	TitleRu  string    `db:"title_ru" json:"title_ru"`
	StartsAt time.Time `db:"starts_at" json:"starts_at"`
	EndsAt   time.Time `db:"ends_at" json:"ends_at"`
}

func (q *Queries) GetHike(ctx context.Context, id int32) (GetHikeRow, error) {
	row := q.db.QueryRow(ctx, getHike, id)
	var i GetHikeRow
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const listActualHikes = `-- name: ListActualHikes :many
SELECT id, title_ru, description_ru, starts_at, ends_at, image_path
FROM hikes
WHERE is_published = true AND ends_at >= now()
ORDER BY starts_at ASC
LIMIT $1 OFFSET $2
`

type ListActualHikesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListActualHikesRow struct {
	ID            int32       `db:"id" json:"id"`
	TitleRu       string      `db:"title_ru" json:"title_ru"`
	DescriptionRu string      `db:"description_ru" json:"description_ru"`
	StartsAt      time.Time   `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time   `db:"ends_at" json:"ends_at"`
	ImagePath     pgtype.Text `db:"image_path" json:"image_path"`
}

func (q *Queries) ListActualHikes(ctx context.Context, arg ListActualHikesParams) ([]ListActualHikesRow, error) {
	rows, err := q.db.Query(ctx, listActualHikes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActualHikesRow
	for rows.Next() {
		var i ListActualHikesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.DescriptionRu,
			&i.StartsAt,
			&i.EndsAt,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeBookingInProgress = `-- name: TakeBookingInProgress :one
UPDATE bookings
SET
    status = $2,
    taken_by_admin_id = $3,
    taken_at = now()
WHERE id = $1 AND status = $4
RETURNING id
`

type TakeBookingInProgressParams struct {
	ID             int32       `db:"id" json:"id"`
	Status         string      `db:"status" json:"status"`
	TakenByAdminID pgtype.Int4 `db:"taken_by_admin_id" json:"taken_by_admin_id"`
	ExpectedStatus string      `db:"expected_status" json:"expected_status"`
}

func (q *Queries) TakeBookingInProgress(ctx context.Context, arg TakeBookingInProgressParams) (int32, error) {
	row := q.db.QueryRow(ctx, takeBookingInProgress,
		arg.ID,
		arg.Status,
		arg.TakenByAdminID,
		arg.ExpectedStatus,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET
    status = $2
WHERE id = $1 AND status = $3
RETURNING id
`

type UpdateBookingStatusParams struct {
	ID       int32  `db:"id" json:"id"`
	Status   string `db:"status" json:"status"`
	Status_2 string `db:"status_2" json:"status_2"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status, arg.Status_2)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO telegram_users (tg_user_id, tg_username, full_name, lang)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tg_user_id)
DO UPDATE SET
    tg_username = EXCLUDED.tg_username,
    full_name   = EXCLUDED.full_name,
    lang        = EXCLUDED.lang
RETURNING id
`

type UpsertTelegramUserParams struct {
	TgUserID   int64       `db:"tg_user_id" json:"tg_user_id"`
	TgUsername pgtype.Text `db:"tg_username" json:"tg_username"`
	FullName   pgtype.Text `db:"full_name" json:"full_name"`
	Lang       string      `db:"lang" json:"lang"`
}

func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.TgUserID,
		arg.TgUsername,
		arg.FullName,
		arg.Lang,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
