// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: hikes.sql

package client

import (
	"context"
	"time"
)

const listActualHikes = `-- name: ListActualHikes :many
SELECT id, title_ru, description_ru, starts_at, ends_at
FROM hikes
WHERE is_published = true AND ends_at >= now()
ORDER BY starts_at ASC
LIMIT $1 OFFSET $2
`

type ListActualHikesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListActualHikesRow struct {
	ID            int32     `db:"id" json:"id"`
	TitleRu       string    `db:"title_ru" json:"title_ru"`
	DescriptionRu string    `db:"description_ru" json:"description_ru"`
	StartsAt      time.Time `db:"starts_at" json:"starts_at"`
	EndsAt        time.Time `db:"ends_at" json:"ends_at"`
}

func (q *Queries) ListActualHikes(ctx context.Context, arg ListActualHikesParams) ([]ListActualHikesRow, error) {
	rows, err := q.db.Query(ctx, listActualHikes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActualHikesRow
	for rows.Next() {
		var i ListActualHikesRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.DescriptionRu,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
