// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package client

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID        int32     `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Booking struct {
	ID             int32              `db:"id" json:"id"`
	HikeID         int32              `db:"hike_id" json:"hike_id"`
	UserID         int32              `db:"user_id" json:"user_id"`
	Status         string             `db:"status" json:"status"`
	Note           pgtype.Text        `db:"note" json:"note"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	TakenByAdminID pgtype.Int4        `db:"taken_by_admin_id" json:"taken_by_admin_id"`
	TakenAt        pgtype.Timestamptz `db:"taken_at" json:"taken_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
}

type Hike struct {
	ID             int32          `db:"id" json:"id"`
	TitleRu        string         `db:"title_ru" json:"title_ru"`
	TitleEn        pgtype.Text    `db:"title_en" json:"title_en"`
	DescriptionRu  string         `db:"description_ru" json:"description_ru"`
	DescriptionEn  pgtype.Text    `db:"description_en" json:"description_en"`
	StartsAt       time.Time      `db:"starts_at" json:"starts_at"`
	EndsAt         time.Time      `db:"ends_at" json:"ends_at"`
	PhotoFileID    pgtype.Text    `db:"photo_file_id" json:"photo_file_id"`
	IsPublished    bool           `db:"is_published" json:"is_published"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	ImagePath      pgtype.Text    `db:"image_path" json:"image_path"`
	PriceGel       int32          `db:"price_gel" json:"price_gel"`
	ElevationGainM pgtype.Int4    `db:"elevation_gain_m" json:"elevation_gain_m"`
	DistanceKm     pgtype.Numeric `db:"distance_km" json:"distance_km"`
	PreviewRu      string         `db:"preview_ru" json:"preview_ru"`
}

type Payment struct {
	ID          int32          `db:"id" json:"id"`
	BookingID   int32          `db:"booking_id" json:"booking_id"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	Currency    string         `db:"currency" json:"currency"`
	ProofFileID pgtype.Text    `db:"proof_file_id" json:"proof_file_id"`
	Status      string         `db:"status" json:"status"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
}

type TelegramUser struct {
	ID         int32       `db:"id" json:"id"`
	TgUserID   int64       `db:"tg_user_id" json:"tg_user_id"`
	TgUsername pgtype.Text `db:"tg_username" json:"tg_username"`
	FullName   pgtype.Text `db:"full_name" json:"full_name"`
	Lang       string      `db:"lang" json:"lang"`
	IsAdmin    bool        `db:"is_admin" json:"is_admin"`
	CreatedAt  time.Time   `db:"created_at" json:"created_at"`
}
