// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: notification.sql

package client

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingNotifications = `-- name: ClaimPendingNotifications :many
WITH pending AS (
    SELECT id
    FROM notifications
    WHERE status = 'pending'
    AND (
        next_retry_at IS NULL
        OR next_retry_at <= NOW()
    )
    ORDER BY created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE notifications AS n
SET
    status = 'processing',
    attempts = n.attempts + 1,
    last_attempt_at = NOW()
FROM pending
WHERE n.id = pending.id
RETURNING
    n.id,
    n.recipient_tg_user_id,
    n.type,
    n.payload,
    n.attempts,
    n.created_at
`

type ClaimPendingNotificationsRow struct {
	ID                int64     `db:"id" json:"id"`
	RecipientTgUserID int64     `db:"recipient_tg_user_id" json:"recipient_tg_user_id"`
	Type              string    `db:"type" json:"type"`
	Payload           []byte    `db:"payload" json:"payload"`
	Attempts          int32     `db:"attempts" json:"attempts"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ClaimPendingNotifications(ctx context.Context, limit int32) ([]ClaimPendingNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingNotificationsRow
	for rows.Next() {
		var i ClaimPendingNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientTgUserID,
			&i.Type,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :execrows
UPDATE notifications
SET
    status = 'failed',
    last_error = $1,
    failed_at = NOW(),
    next_retry_at = NULL
WHERE id = $2
    AND status = 'processing'
`

type MarkNotificationFailedParams struct {
	LastError pgtype.Text `db:"last_error" json:"last_error"`
	ID        int64       `db:"id" json:"id"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationFailed, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationSent = `-- name: MarkNotificationSent :execrows
UPDATE notifications
SET
    status = 'sent',
    sent_at = NOW(),
    last_error = NULL,
    next_retry_at = NULL

WHERE id = $1
    AND status = 'processing'
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseNotificationForRetry = `-- name: ReleaseNotificationForRetry :execrows
UPDATE notifications
SET
    status = 'pending',
    last_error = $1,
    next_retry_at = $2
WHERE id = $3
    AND status = 'processing'
`

type ReleaseNotificationForRetryParams struct {
	LastError   pgtype.Text        `db:"last_error" json:"last_error"`
	NextRetryAt pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	ID          int64              `db:"id" json:"id"`
}

func (q *Queries) ReleaseNotificationForRetry(ctx context.Context, arg ReleaseNotificationForRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseNotificationForRetry, arg.LastError, arg.NextRetryAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
